name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push App image
      run: |
        docker build -t app -f Dockerfile .
        docker tag app:latest 403539841960.dkr.ecr.us-east-1.amazonaws.com/webapp-clo835:latest
        docker push 403539841960.dkr.ecr.us-east-1.amazonaws.com/webapp-clo835:latest
    - name: Build, tag, and push MySQL image
      run: |
        docker build -t mysql -f Dockerfile_mysql .
        docker tag mysql:latest 403539841960.dkr.ecr.us-east-1.amazonaws.com/mysql-clo835:latest
        docker push 403539841960.dkr.ecr.us-east-1.amazonaws.com/mysql-clo835:latest
